### ISSUE TITLE
file.zip

### ISSUE THREAD

**Issue by fvalle1** [DrewNF/Latex-Template-Polito#1]
ciao!
posso suggerirti di non usare file.zip, difficilmente gestibili con git, ma di lasciare i file scompattati, magari organizzati in cartelle.
In questo modo sarebbero visualizzatili anche dall'interfaccia online ed eventuali modifiche sarebbero ben evidenziate nella git history.

**Comment by DrewNF** [comment]
Fatto! 👍 ho lasciato il file .zip come backup originale in caso di bisogno 😄
